[workspace]

members = [
    "compiler/kona",

    # Compiler:
    "compiler/kona-ast",

    # Utilities:
    "compiler/kona-diagnostic",
    "compiler/kona-arena",
    "compiler/kona-proc-macros",
]
