[package]
name = "kona-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
kona-diagnostic = { path = "../kona-diagnostic" }
kona-arena = { path = "../kona-arena" }
kona-proc-macros = { path = "../kona-proc-macros" }
